### ISSUE TITLE
Bookdown Build Error

### ISSUE THREAD

**Issue by chrisdaaz** [CassieConnected/minibookdown#2]
I see a few things that might need to change with your markdown files to get your book building properly.

## Fix the image reference in `01-introduction.Rmd` file

In your introduction chapter, you have a reference to an image you added: 

```
![Gratuitous photo of Buster](https://user-images.githubusercontent.com/76963516/105187421-c3eaba80-5b00-11eb-8916-1b1d665adef2.jpg)
```

Because you have the image available at the root of your repository, you can reference it like with the filename:

```
![Gratuitous photo of Buster](202006_Buster_Hotel.jpg)
```

## Fix the Chapter 2 filename

Chapter two filename has a space and is missing an file extension. Change it to this: `02-assemblages.Rmd`

Those two things stand out to me. You can find more information about Markdown syntax [here](https://bookdown.org/yihui/bookdown/markdown-syntax.html)

**Comment by CassieConnected** [comment]
Thank you- you set me straight and everything committed without issue!
